### ISSUE TITLE
Viewpoints

### ISSUE THREAD

**Issue by nadiasalgado** [nadiasalgado/sentimentanalysis2019#3]
Im not sure if what I'm looking at is what we need, https://github.com/planetlabs/viewpoints and https://github.com/creonlevit/viewpoints

**Comment by NqobileMhlanga** [comment]
I looked up the definition of viewpoints (for software engineering). I think the ones you have shared are for the specific projects, we need our own. This is where I found the definition https://www.viewpoints-and-perspectives.info/home/viewpoints/
